### ISSUE TITLE
Error when text file is selected in TOC

### ISSUE THREAD

**Issue by gdherbert** [gdherbert/FindDuplicatesAddIn#2]
Unhandled Exception occurs trying to Find Duplicates when text file is selected in TOC.
Field list is successful. Also No Field Selected error when first field is selected rather than unhandled exception.

Error HRESULT E_FAIL has been returned from a call to a COM component.

*************\* Exception Text **************
System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at ESRI.ArcGIS.Geodatabase.TableSortClass.set_Table(ITable Table)
   at FindDuplicatesAddIn.frmFindDups.btnFindDups_Click(Object sender, EventArgs e) in C:\Users\Grant\Documents\Coding ESRI\Addins ArcMap\FindDuplicatesAddIn\FindDuplicatesAddIn\frmFindDups.vb:line 243
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by gdherbert** [comment]
not going to fix as will not work in pro in current form.
